Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -16,7 +16,8 @@ jobs:
       - name: Test
         shell: bash
         run: |
-        
-          git show-branch -a 2>/dev/null
-          PARENT_BRANCH=$(git show-branch -a 2>/dev/null | grep -q '\*' | grep -q -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
+          # Note: { grep * || :; } is to prevent exit code of 1 on zero-match from halting workflow
+          PARENT_BRANCH=$(git show-branch -a 2>/dev/null | { grep '\*' || :; } | { grep -v `git rev-parse --abbrev-ref HEAD` || :; } | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
           echo $PARENT_BRANCH
+
+
